- name: cart module
  hosts: cart
  become: yes
  tasks:
  - name: disabling the old module
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enabling the old module
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing the nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: creating user
    ansible.builtin.user:
      name: roboshop
      system: yes
      shell: /sbin/nologin
      home: /app

  - name: creating directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: get file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip

  - name: unzipping
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes
  
  - name: installing npm
    community.general.npm:
      path: /app

  - name: copying the file
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: reloading the daemon
    ansible.builtin.systemd_service:
      daemon_reload: true
    
  - name: enabling and start
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes
